name: pfss

channels:
  - conda-forge

dependencies:
  - python == 3.9.2
  - pip == 21.0.1
  - nodejs == 15.14.0
  - pip:
    - drms == 0.6.1
    - sunpy == 2.1.4
    - numpy == 1.20.2
    - matplotlib == 3.4.1
    - scipy == 1.6.2
    - astropy == 4.2.1
    - pfsspy == 0.6.6
    - beautifulsoup4 == 4.9.3
    - lxml == 4.6.3
    - zeep == 4.0.0
    - parfive == 1.3.0
    - jupyterlab == 3.0.14
    - ipywidgets == 7.6.3